---
title: elementary AppCenter
summary: Get apps on AppCenter, the open, pay-what-you-want app store for indie developers.
image: "https://elementary.io/images/screenshots/appcenter.jpg"
separator: "&sdot;"
color:
  primary: "#485a6c"
  primary-text: "#fff"

collections:
  apps:
    title: Apps
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: apps
    values:
      layout: app

markdown: kramdown

permalink: pretty
sass:
  style: compressed

